services:
  frontend:
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product_db
    volumes:
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 8306:3306
